import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/foundation.dart';
import '../models/trip.dart';

class FirestoreService {
  final FirebaseFirestore _firestore = FirebaseFirestore.instance;

  /// Upload a new trip to Firestore.
  ///
  /// Returns the generated Firestore document ID.
  Future<String> uploadTrip(Trip trip, String firebaseUserId) async {
    final String collectionPath = 'users/$firebaseUserId/trips';
    final User? currentUser = FirebaseAuth.instance.currentUser;

    debugPrint('========== FIRESTORE UPLOAD START ==========');
    debugPrint(
      'Firebase Auth State : ${currentUser != null ? "Authenticated" : "Unauthenticated"}',
    );
    debugPrint('Firebase UID        : $firebaseUserId');
    debugPrint('Destination         : ${trip.destination}');
    debugPrint('Number of days      : ${trip.numberOfDays}');
    debugPrint('Budget              : ${trip.budget}');
    debugPrint('Number of people    : ${trip.numberOfPeople}');
    debugPrint('Firestore path      : $collectionPath');
    debugPrint('============================================');

    try {
      final tripData = trip.toMap();
      // Prepare payload for Firestore
      tripData['updatedAt'] = FieldValue.serverTimestamp();
      tripData['userId'] = firebaseUserId; // Use actual Firebase UID string
      tripData.remove('id'); // Local SQLite ID is not uploaded
      tripData.remove('cloudId'); // Will be generated by Firestore

      final documentReference = await _firestore
          .collection('users')
          .doc(firebaseUserId)
          .collection('trips')
          .add(tripData);

      final String cloudId = documentReference.id;

      debugPrint('========== FIRESTORE UPLOAD SUCCESS ==========');
      debugPrint('Cloud document ID: $cloudId');
      debugPrint('Destination      : ${trip.destination}');
      debugPrint('==============================================');

      return cloudId;
    } catch (e, stackTrace) {
      debugPrint('========== FIRESTORE UPLOAD FAILED ==========');
      debugPrint('Error      : $e');
      debugPrint('Stack trace: $stackTrace');
      debugPrint('=============================================');
      rethrow;
    }
  }

  /// Update an existing trip in Firestore.
  Future<void> updateTripInCloud(Trip trip, String firebaseUserId) async {
    if (trip.cloudId == null || trip.cloudId!.isEmpty) {
      throw Exception('No cloudId provided for update');
    }

    final String collectionPath = 'users/$firebaseUserId/trips/${trip.cloudId}';
    final User? currentUser = FirebaseAuth.instance.currentUser;

    debugPrint('========== FIRESTORE UPDATE START ==========');
    debugPrint(
      'Firebase Auth State : ${currentUser != null ? "Authenticated" : "Unauthenticated"}',
    );
    debugPrint('Firebase UID        : $firebaseUserId');
    debugPrint('Cloud Document ID   : ${trip.cloudId}');
    debugPrint('Destination         : ${trip.destination}');
    debugPrint('Firestore path      : $collectionPath');
    debugPrint('============================================');

    try {
      final tripData = trip.toMap();
      tripData['updatedAt'] = FieldValue.serverTimestamp();
      tripData['userId'] = firebaseUserId;
      tripData.remove('id');
      tripData.remove('cloudId');

      await _firestore
          .collection('users')
          .doc(firebaseUserId)
          .collection('trips')
          .doc(trip.cloudId)
          .update(tripData);

      debugPrint('========== FIRESTORE UPDATE SUCCESS ==========');
      debugPrint('Cloud document ID: ${trip.cloudId}');
      debugPrint('==============================================');
    } catch (e, stackTrace) {
      debugPrint('========== FIRESTORE UPDATE FAILED ==========');
      debugPrint('Error      : $e');
      debugPrint('Stack trace: $stackTrace');
      debugPrint('=============================================');
      rethrow;
    }
  }

  /// Retrieve all raw trip maps belonging to a user from Firestore.
  Future<List<Map<String, dynamic>>> getRawTripsFromCloud(
    String firebaseUserId,
  ) async {
    try {
      final snapshot = await _firestore
          .collection('users')
          .doc(firebaseUserId)
          .collection('trips')
          .get();

      return snapshot.docs.map((doc) {
        final data = Map<String, dynamic>.from(doc.data());
        data['cloudId'] = doc.id;

        if (data['updatedAt'] is Timestamp) {
          data['updatedAt'] = (data['updatedAt'] as Timestamp)
              .toDate()
              .toIso8601String();
        }
        if (data['createdAt'] is Timestamp) {
          data['createdAt'] = (data['createdAt'] as Timestamp)
              .toDate()
              .toIso8601String();
        }

        return data;
      }).toList();
    } catch (e, stackTrace) {
      debugPrint('Failed to get cloud trips: $e\n$stackTrace');
      rethrow;
    }
  }

  /// Delete a cloud trip.
  Future<void> deleteTripFromCloud(
    String cloudId,
    String firebaseUserId,
  ) async {
    try {
      await _firestore
          .collection('users')
          .doc(firebaseUserId)
          .collection('trips')
          .doc(cloudId)
          .delete();
      debugPrint('Deleted trip $cloudId from cloud.');
    } catch (e, stackTrace) {
      debugPrint('Failed to delete cloud trip $cloudId: $e\n$stackTrace');
      rethrow;
    }
  }
}
