// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-SfJ24SfkH1F50K8JyHVEzzEcXHXeBsM',
    appId: '1:32455670259:web:062a40ae775bedd600fa86',
    messagingSenderId: '32455670259',
    projectId: 'wander-genie-45a36',
    authDomain: 'wander-genie-45a36.firebaseapp.com',
    storageBucket: 'wander-genie-45a36.firebasestorage.app',
    measurementId: 'G-T2PPN6MEPG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8j73XMDXyPNHbRYTxovWKeSnc4LmjhFM',
    appId: '1:32455670259:android:1ff58b36fe87cb7d00fa86',
    messagingSenderId: '32455670259',
    projectId: 'wander-genie-45a36',
    storageBucket: 'wander-genie-45a36.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCy6DyqUW6HY0CZzvwygQgnXh5daxCMkkg',
    appId: '1:32455670259:ios:58bd25214b41c6fa00fa86',
    messagingSenderId: '32455670259',
    projectId: 'wander-genie-45a36',
    storageBucket: 'wander-genie-45a36.firebasestorage.app',
    iosBundleId: 'com.example.travelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCy6DyqUW6HY0CZzvwygQgnXh5daxCMkkg',
    appId: '1:32455670259:ios:58bd25214b41c6fa00fa86',
    messagingSenderId: '32455670259',
    projectId: 'wander-genie-45a36',
    storageBucket: 'wander-genie-45a36.firebasestorage.app',
    iosBundleId: 'com.example.travelApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-SfJ24SfkH1F50K8JyHVEzzEcXHXeBsM',
    appId: '1:32455670259:web:74dd68c86f5ff81500fa86',
    messagingSenderId: '32455670259',
    projectId: 'wander-genie-45a36',
    authDomain: 'wander-genie-45a36.firebaseapp.com',
    storageBucket: 'wander-genie-45a36.firebasestorage.app',
    measurementId: 'G-Y33K288FW8',
  );
}
